version: "3.8"
services:
  excalidraw:
    build:
      context: .
      target: build
      args:
        - NODE_ENV=development
    container_name: excalidraw-dev
    ports:
      - "5173:5173"
      - "3000:3000"
    restart: always
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - DOCKER=true
      - VITE_APP_AI_BACKEND=https://oss-ai.excalidraw.com
    volumes:
      - ./:/opt/node_app
      - /opt/node_app/node_modules
      - /opt/node_app/excalidraw-app/node_modules
    command: yarn start
