version: "3.8"

services:
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=development
      target: deps
    container_name: excalidraw
    ports:
      - "3000:3000"
    restart: on-failure
    command: npm run start
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules

volumes:
  notused:
