name: Auto release preview @excalidraw/excalidraw-preview
on:
  pull_request:

jobs:
  Auto-release-excalidraw-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Set up publish access
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Auto release preview
        id: "autorelease"
        run: |
          yarn add @actions/core
          yarn autorelease preview ${{ github.event.pull_request.number }}

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "excalibot"
          body-includes: Preview version released [@excalidraw/excalidraw-preview](https://npmjs.com/@excalidraw/excalidraw-preview)
      - name: Create release comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview version has been shipped :rocket:
            Below are the shipped versions :down
            ${{ steps.autorelease.outputs.version }}

      - name: Update release comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ${{ steps.autorelease.outputs.version }}
          reactions: hooray
