name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install and lint
        run: |
          yarn install
          yarn test:other
          yarn test:code
          yarn test:typecheck
