name: "Bundle Size check @excalidraw/excalidraw"
# on:
#  pull_request:
#    branches:
#      - master

# Now, this workflow will ONLY run if you manually click
# the "Run workflow" button in the Actions tab.
on: workflow_dispatch

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
      - name: Install in packages/excalidraw
        run: yarn
        working-directory: packages/excalidraw
        env:
          CI: true
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build:esm
          skip_step: install
          directory: packages/excalidraw
